services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
    networks:
      - test_appnet

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB:  ${POSTGRES_DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - test_appnet
volumes:
  pgdata:

networks:
  test_appnet:
    driver: bridge
